### ISSUE TITLE
Rethink Fatal exits inside of the Authenticate method

### ISSUE THREAD

**Issue by sonnysideup** [sonnysideup/go-gremlin#3]
It's probably better to return an error here. #derp

**Comment by sonnysideup** [comment]
Word, thx dude.

I made a couple of minor changes that you should be aware of:

1. I added the project to [TravisCI](https://travis-ci.org/sonnysideup/go-gremlin), so yay for continuous testing. We can add linting, reportcard checking, etc.... later
2. The second change I made was to move all of the files from the `gremlin` dir directly into the root. Consumers will still invoke the lib via `gremlin.*` since that's the name of the package, but this change simplifies the directory structure and is honestly more idiomatic IMO.

The 💩 part of this change is that I did it directly onto **master** so you'll just have to reconcile that before merging in your PR. My bad, I'm a turd. #shameshameshame.

**Comment by sebradloff** [comment]
No worries man. Simple rebase did the trick. 
Love the TravisCI integration.
Agreed with the moving of all files in the `gremlin` dir into root. Looking forward to your comments on the PR.

**Comment by sonnysideup** [comment]
Addressed in PR #4
